name: Run Reddit Cleaner
on:
  schedule:
  # Run every 2 weeks on cron
  - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python Env
      run: python -m pip install -r requirements.txt

    - name: Run Cleaner
      run: python clean.py
      env:
        BI: ${{secrets.BI}}
        BS: ${{secrets.BS}}
        P: ${{secrets.P}}
        AUTHOR: ${{secrets.AUTHOR}}
